version: '3'

services:
  webcalc:
    image: webcalc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py
      - ./reqs.txt:/app/reqs.txt
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
