version: '3'

services:
  webcalc:
    image: webcalc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    volumes:
      - ./main.py:/app/main.py
      - ./reqs.txt:/app/reqs.txt
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--reload", "--port", "10000"]
